# TP 01 : configuration Nginx en HTTPS
# À compléter par toi. Dans le conteneur :
#   - le certificat est dans  /etc/nginx/certs/tp01.test.pem
#   - la clé privée est dans  /etc/nginx/certs/tp01.test-key.pem
#   - l'app Express répond sur http://app:3000 ("app" = nom du service Docker)

server {
    listen 443 ssl; # TODO 1 : écouter sur le port 443, en TLS

    server_name tp01.test; # TODO 2 : répondre pour le nom de domaine tp01.test

    ssl_certificate ../certs/tp01.test.pem; # TODO 3 : indiquer le certificat

    ssl_certificate_key ../certs/tp01.test-key.pem; # TODO 4 : indiquer la clé privée

    location / {
        proxy_pass http://app:3000; # TODO 5 : transmettre les requêtes à l'app Express
    }
}
